export enum ServiceLevel {
  REALID0001 = 'REALID0001',
  REALID0002 = 'REALID0002',
  REALID0003 = 'REALID0003',
  REALID0004 = 'REALID0004',
  REALID0009 = 'REALID0009',
  REALID0011 = 'REALID0011',
  REALID0012 = 'REALID0012',
}

export enum ResultCode {
  SUCCESS = 'SUCCESS',
  HIGH_RISK = 'HIGH_RISK',
  ACCOUNT_SERVICE_SUSPEND = 'ACCOUNT_SERVICE_SUSPEND',
  DEVICE_NOT_SUPPORT = 'DEVICE_NOT_SUPPORT',
  OS_NOT_SUPPORT = 'OS_NOT_SUPPORT',
  SDKVERSION_NOT_SUPPORT = 'SDKVERSION_NOT_SUPPORT',
  INVALID_ARGUMENT = 'INVALID_ARGUMENT',
  SYSTEM_ERROR = 'SYSTEM_ERROR',
}

export enum RealIdResultStatus {
  SUCCESS = 'S',
  FAILURE = 'F',
}

export enum YesNo {
  Y = 'Y',
  N = 'N',
}

export enum ResultStatus {
  S = 'S',
  F = 'F',
}
